### PR TITLE
>vB/s< to >B/s<

### PR DESCRIPTION
**Pull request by plowsof**

### CODE REVIEW

**Comment by HardenedSteel** [comment]
Are there any calculation code about converting B/s to vB/s ? If yes it might keep show sizes in vB/s.

**Comment by plowsof** [comment]
Yes, you are 100% correct, just trying to get the ball rolling with a text replace :smile: 
this looks relevant :shrug:  https://github.com/Rucknium/bchmempool/blob/bch-dev/frontend/src/app/shared/pipes/bytes-pipe/vbytes.pipe.ts

**Comment by Rucknium** [comment]
@plowsof The good news is that this PR appears to have broken nothing. The bad news is that it appears to have had no effect on the website display.

**Comment by Rucknium** [comment]
@plowsof Maybe try >sat/vB< to >sat/vB< ?

**Pull request merged**
